### ISSUE TITLE
Can't install; checkout from SF broken; looks like it is unstable

### ISSUE THREAD

**Issue by slarson** [NeuroML/jNeuroML#26]
I try this:

`svn checkout svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar`

I get this: 

```
svn: E000061: Unable to connect to a repository at URL 'svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar'
svn: E000061: Can't connect to host 'svn.code.sf.net': Connection refused
```

Looks like SF is having [a ton of downtime](https://twitter.com/sfnet_ops/status/622236074052464641)...  Time to move this to GitHub?

**Comment by pgleeson** [comment]
Have made a binary release and updated the docs here: https://github.com/NeuroML/jNeuroML to point to the latest zip file release.

**Comment by pgleeson** [comment]
Closes, as the binaries are now on GitHub
