### ISSUE TITLE
jnml sometimes crashes when timestep is too large

### ISSUE THREAD

**Issue by JustasB** [NeuroML/jNeuroML#29]
In some cases, the program crashes with a long table, the contents of which may not provide enough information that the time step is the problem. 

New users of jnml may be using a large timestep to increase the performance (and productivity) of their model, but instead may get slowed down by trying to debug the crashes.

**In the cases where infinities are causing the problem, consider adding a suggestion to reduce the time step** in addition to the current output (the exception and the table). 

If this were implemented, it would reduce the learning curve for new users.

**Comment by pgleeson** [comment]
Good suggestion. Added this check to the [development branch of jLEMS](https://github.com/LEMS/jLEMS/blob/16e73426e6c11f2072f059fd23749b20d708148c/src/main/java/org/lemsml/jlems/core/sim/Sim.java#L275). Will be in binary release of jNeuroML soon.
