### ISSUE TITLE
exported svg file svg tag should have viewBox parameter

### ISSUE THREAD

**Issue by JustasB** [NeuroML/jNeuroML#33]
When using jnml -svg the resulting file does not include the `<svg viewBox="0 0 width height">` parameter, resulting in view issue below (using Chrome):

![screen shot 2016-01-06 at 4 46 54 pm](https://cloud.githubusercontent.com/assets/10732358/12158223/49c46b82-b495-11e5-8386-ed60dcd04f29.png)

Adding the parameter, manually, fixes the display issue:
![screen shot 2016-01-06 at 4 46 07 pm](https://cloud.githubusercontent.com/assets/10732358/12158227/59751018-b495-11e5-9680-98725b5228d8.png)

The values for width and height would need to be determined at the time of svg generation.

**Comment by pgleeson** [comment]
It looks like this is no longer an issue with Chrome, large svg files can be viewed correctly (might require zooming out). Will leave this open and it's no harm to add the viewBox param at some point.

**Comment by pgleeson** [comment]
Fixed in development
