### ISSUE TITLE
JNeuroMLJar in README.md

### ISSUE THREAD

**Issue by theiera** [NeuroML/jNeuroML#34]
In this sentence of the README.md:
"Adding the environment variable JNML_HOME, pointing to the jNeuroMLJar folder, as well as adding this path to the PATH variable will let you use the jnml utility from any folder."
 The jNeuroMLJar should be jNeuroML.

**Comment by pgleeson** [comment]
Good point, though the directory is jNeuroMLJar when you install via the binary release, e.g. https://github.com/NeuroML/jNeuroML/releases/download/v0.7.2-preBeta4/jNeuroML.zip, but it will be jNeuroML for the source based install. 

A better name might be jNeuroML also for the directory in the zip file. I'll make this change.
