### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by lukeczapla** [NeuroML/jNeuroML#37]
Hello all, I am having trouble with the getNeuroML.py script (just with the master repo, but I ran into a problem trying the development too).  It throws an error in org.neuroml.import, and so I did "mvn install" in that folder to get the full details of the error:

```
Downloading: https://repo.maven.apache.org/maven2/org/biojava/core/1.8.1/core-1.8.1.jar
Downloading: http://www.biojava.org/download/maven/org/biojava/core/1.8.1/core-1.8.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.341 s
[INFO] Finished at: 2016-04-16T13:56:57-04:00
[INFO] Final Memory: 9M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project org.neuroml.import: Could not resolve dependencies for project org.neuroml.import:org.neuroml.import:jar:1.3.1: Could not find artifact org.biojava:core:jar:1.8.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

```

Could anyone help?  Thanks!

**Comment by pgleeson** [comment]
This is an issue pulling some of the Maven jars for Biojava (required for jSBML in org.neuroml.import). See: https://github.com/biojava/biojava/issues/451.

I will prepare a new binary release while this is being fixed...

**Comment by pgleeson** [comment]
@lukeczapla try the latest release here: https://github.com/NeuroML/jNeuroML/releases. All the latest c302 examples should run with this.

**Comment by lukeczapla** [comment]
Thank you, I have a running version of the binary Jar file already but I really want to be able to work with the source.   Do you know of any ways I can modify the Maven files to point to a manual downloaded version of Biojava?

**Comment by lukeczapla** [comment]
@pgleeson I was able to get it to compile by changing the dependency to jSBML 1.1 and installing that in the local repository (jsbml-1.1-with-dependencies.jar) and editing pom.xml, but yes, it was only version 0.5.2 that didn't support the new stuff that you did and couldn't parse the C1 gapjunction data.   I would like to be able to work with the code in Eclipse, it is a pretty huge program but I am working with a student here who would like to learn more about how the simulations work in terms of code.  Thanks!

**Comment by pgleeson** [comment]
@lukeczapla this has been resolved now, see https://github.com/biojava/biojava/issues/451. Let me know if you have any more problems with the standard install on the development branches.

**Comment by pgleeson** [comment]
Is this resolved for you now @lukeczapla?

**Comment by lukeczapla** [comment]
Yes, thank you very much!
