### ISSUE TITLE
How to put conditional logic in NET_RECEIVE block (or before SOLVE) using LEMS?

### ISSUE THREAD

**Issue by JustasB** [NeuroML/jNeuroML#39]
I have a .mod file of a synapse with a NET_RECEIVE block that I'm converting to LEMS.

In this block, there are several conditional assignment statements to variables A & B.
After the NET_RECEIVE logic is complete, the DERIVATIVE block is executed where A & B rates are updated.
Then variables i & g are updated in the BREAKPOINT block.

So the original sequence is NET_RECEIVE -> conditional update -> DERIVATIVE -> BREAKPOINT

However, expressing the conditional statements in LEMS, puts them in BREAKPOINT block in translated .mod file, AFTER the DERIVATIVE block has executed. I need a way to execute those conditional statements BEFORE the DERIVATIVE block.

For example, this:
```
            <OnEvent port="in">
                <StateAssignment variable="spikeProcessed" value="0" />
            </OnEvent>
            
            <OnCondition test="spikeProcessed .eq. 0 .and. timeSinceSpike .lt. LTPlimit">
                <StateAssignment variable="pstep" value="pstepPlusOne"/>
            </OnCondition>
```
Results in:
```
BREAKPOINT {
    
    SOLVE states METHOD cnexp
    
    if (spikeProcessed  == 0 &&  timeSinceSpike  <=  LTPlimit) {
        pstep = pstepPlusOne ? standard OnCondition
    }
}
```
I need the IF statement before the SOLVE statement.

Ideally, putting the conditional statements inside the OnEvent tag would work:
```
            <OnEvent port="in">
                <StateAssignment variable="spikeProcessed" value="0" />
                
                <OnCondition test="spikeProcessed .eq. 0 .and. timeSinceSpike .lt. LTPlimit">
                    <StateAssignment variable="pstep" value="pstepPlusOne"/>
                </OnCondition>
                
            </OnEvent>
```
But as of now, jnml ignores the OnCondition tag that's in OnEvent tag.

**Comment by pgleeson** [comment]
@JustasB do you have an example that carried out the correct sequence in jNeuroML, i.e. with the reference LEMS behaviour? It's quite possible that not all scenarios are covered in the mapping to Neuron, but certainly the correct behaviour running in jNeuroML is a prerequisite.

**Comment by JustasB** [comment]
@pgleeson No, that's what I'm trying to do. The only working example is the original NEURON model.

I need to implement the lines in NET_RECEIVE here: 
https://github.com/JustasB/Mig3DTest/blob/master/NEURON/fi.mod#L104 
in LEMS. However, I have not found a way to do it.

The only way I found in LEMS (above), puts the logic _after_ SOLVE statement in BREAKPOINT. I need those lines to execute _before_ the SOLVE statement.

**Comment by JustasB** [comment]
As far as I can tell, LEMS does not support OnCondition statements inside OnEvent tags (e.g. it's not listed here: http://lems.github.io/LEMS/elements.html and they get ignored by jnml).

There also does not appear to be a way to specify an OnCondition statement to be evaluated before the TimeDerivative statements.

**Comment by pgleeson** [comment]
The OnCondition statement can't be put into the OnEvent, it's just not supported in LEMS. What you'll probably need to do is break the problem up into (conditional)derivedvariables and state variables. Something like:

make a state var for s
make a ConditionalDerivedVariables called new_s which is evaluated every time step based on the current t and a state variable tlast (and ltdinvl etc)
only when an event is called set s = new_s
maybe you'll need a state var for plast also...

If this works in LEMS/jNeuroML it should be fine in Neuron too...

**Comment by JustasB** [comment]
I was able to solve the problem with a hack similar to the one you described.
