### ISSUE TITLE
Bug in MultiInstantiate when assigning

### ISSUE THREAD

**Issue by dokato** [NeuroML/jNeuroML#40]
Hi,
I try to make a network of LIF neurons with different initial values `v0`. To do this I used `MultiInstantiate`. But the problem appears when I try to assign an initial value like this:

```
20*const_mV * index / (n-1)
```

where `const_mV` is defined as follows (such a solution is due to the fact that it's not possible to use units in LEMS equations):
```
<Constant dimension="voltage" name="const_mV" symbol="const_mV" value="0.001"/>
```

For whatever reason LEMS doesn't accept the constant const_mV in the value of the Assign for v0. I don't get it why...

Here is an example with reproduces the error:

https://gist.github.com/dokato/710ff6448029283ddfe0354d3dca7044

To overcome that I used an attempt with an additional parameter `base_v0` with a number with unit assigned to it:

```
  <ComponentType name="lifneurons">
        <Parameter dimension="none" name="n"/>
        <Parameter dimension="time" name="tau_p"/>
        <Parameter dimension="voltage" name="base_v0"/>
        <Structure>
            <MultiInstantiate componentType="neuron1" number="n">
                <Assign property="v0"
                        value=" base_v0 * index / (n-1)"/>
                <Assign property="tau" 
                        value="tau_p"/>
            </MultiInstantiate>
        </Structure>
  </ComponentType>

  <lifneurons id="nrns" n="100" tau_p="10. ms" base_v0="20 mV"/>
```

It works, but when dealing with more values such a bypass can be problematic.

**Comment by pgleeson** [comment]
@dokato I've updated yuour example and added it here: https://github.com/OpenSourceBrain/BrianShowcase/blob/master/LEMS/if_noref.xml. It needed to have the Constant moved to within the ComponentType. This should work now with jnml.

I've also added the use of random() to give random taus.

**Comment by pgleeson** [comment]
@mstimberg suggested a skype next week to catch up on all the Brian-NML2 interactions. Can you mail me regarding this @dokato?

**Comment by pgleeson** [comment]
@dokato ok to close this?

**Comment by dokato** [comment]
Yes, thank you for help!
