### ISSUE TITLE
print statements are only python2 compliant.

### ISSUE THREAD

**Issue by russelljjarvis** [NeuroML/jNeuroML#43]
line: 19  print "Cleaning repos"  seems to be causing problems in python3, but not python2.7
Reason:
Python 3 explicitly treats “print” as a function, which means you have to pass the items you need to print to the function in parentheses in the standard way, or you will get a syntax error.

**Comment by pgleeson** [comment]
https://github.com/NeuroML/jNeuroML/commit/adb2948eb86ffe2beccfb210febf79a137cdd349 has been successfully tested with python 3
