### ISSUE TITLE
More details in build from source instructions

### ISSUE THREAD

**Issue by jonc125** [NeuroML/jNeuroML#47]
The `getNeuroML.py` file builds dependencies, but not (it seems) the jNeuroML Java classes themselves, and running `mvn install` after `getNeuroML.py` gives
```
[ERROR] Failed to execute goal on project jNeuroML: Could not resolve dependencies for project org.neuroml:jNeuroML:jar:0.7.7: Could not find artifact org.neuroml.import:org.neuroml.import:jar:1.4.6 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
suggesting some extra maven setup is needed.

**Comment by pgleeson** [comment]
The getNeuroML.py file should also run mvn install in each of the directories it checks out, or fail. Are you seeing: 

     >>>  Executing: (mvn install) in dir: ../jLEMS

in each java based repo? Can you run: `mvn install` successfully in jLEMS (has no dependencies)?

Note: once getNeuroML.py works with the master branch, be sure to switch to the development branches: python getNeuroML.py development

**Comment by jonc125** [comment]
Yes, I saw mvn running in each dependency - it's just in the jNeuroML folder itself that it doesn't run. I think mvn needs the dependencies installed to a local repository so it can find them when building jNeuroML?

**Comment by jonc125** [comment]
Although org.neuroml.model manages to use one of the other dependencies as its dependency, so I'm not sure what the difference is in their settings...

Ah, the missing dep is org.neuroml.import, which hasn't been built because there was an earlier error (with no message printed to screen) building org.neuroml.export. That one can't find org.lemsml:jlems:jar:0.9.8.6. So looks like the order in which these are built is crucial.

Further investigation reveals that the initial build of jLEMS had been interrupted, and I think subsequent runs didn't try re-building it because the git pull said it was up-to-date. Removing the folder and re-running has let everything build successfully, including jNeuroML itself.

So, the issue is actually that the script isn't robust to failed builds, and doesn't (at least in this case) retry them when it should.

**Comment by sanjayankur31** [comment]
the script seems to be running fine, so we'll close this for the moment and re-open if required.
