### ISSUE TITLE
Simulations longer than a few seconds stall in 0.8.3

### ISSUE THREAD

**Issue by cengique** [NeuroML/jNeuroML#60]
We have an 8 isopotential cell with 5-8 channels each, simulated with a step size 0.01ms. If the simulation is run more than 5000ms, then `jnml` gets slower and slower to the point that it's producing no updates on the plots. There must be a scalability issue with either plotting or storing the data. I already had to increase allocated memory via `export JNML_MAX_MEMORY_LOCAL=4000M`.

**Comment by pgleeson** [comment]
That's probably what I'd expect... It's probably a bottleneck in the plotting that's causing the slowdown. Do you need to plot in realtime? You could run the same scripts with -nogui and it will just save the traces (that should be faster) and analyse them offline. 

Alternatively if it runs in jnml, it should run fine in Neuron (it's good to test that the results match on this anyway). There should be a significant speed up for running, plotting and saving the results when run in Neuron. 

@robertcannon never intended jLEMS (core of jnml) as a heavy duty simulator... it's great for running small networks for relatively short times, but once the models are in valid NeuroML, Neuron (or other supporting platforms...) should be the simulator of choice...
