### ISSUE TITLE
Add prebuilt jar for the new release

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/jNeuroML#65]
I noticed that a pre-built jar isn't available for the NeuroML2 based releases, should we add them, just to make it convenient for users?

**Comment by pgleeson** [comment]
Yes, I've been meaning to do that... Currently the latest development version can be accessed with:

    svn checkout svn://svn.code.sf.net/p/neuroml/code/jNeuroMLJar

which is always preferred to the last full release & fully tested on the 0SB projects. 

I could certainly add pre/beta releases... Will do this next dev release...

**Comment by sanjayankur31** [comment]
Hrm, yes, especially given that the latest jar does not specify that it's built from a snapshot:


```
$ ./jnml -v
 jNeuroML v0.10.0
    org.neuroml.import  v1.7.0
    org.neuroml.export  v1.7.0
    org.neuroml.model   v1.7.0
    jLEMS               v0.10.2
```

If it's built from a snapshot, it should include the git commit in it so that if users do use it and run into issues they can tell us what commit they're at. The ideal scenario would be to have frequent minor/patch releases so we know exactly what users are at. They really shouldn't be using code from master/dev branches unless it's been tagged + released. What do you think?

**Comment by sanjayankur31** [comment]
Is this latest jar pointing to the latest tag?

https://github.com/NeuroML/jNeuroML/releases/tag/NMLv2.0

**Comment by pgleeson** [comment]
No... 
I should have an interm release soon and can ensure there's a release/tag with that. 
The idea of moving all versions to 2.1.xxx etc. is looking more attractive, then I can increase the minor versions more frequently...
