### ISSUE TITLE
jnml-0.10.3: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector

### ISSUE THREAD

**Issue by sanjayankur31** [NeuroML/jNeuroML#71]
Hi!

Got this when running `jnml -validate`:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector (file:/usr/share/java/jNeuroML-0.10.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Version information:

```
$ jnml -version
 jNeuroML v0.10.0
    org.neuroml.import  v1.7.0
    org.neuroml.export  v1.7.0
    org.neuroml.model   v1.7.0
    jLEMS               v0.10.2
```

**Comment by sanjayankur31** [comment]
I dug into this a little, primarily because it adds so much noise to `jnml` and `pynml` outputs. Found this:

https://stackoverflow.com/a/50251510/375067

So, the solution is to use a newer version of jaxb-ri. Now, I'm not sure of how to do that. Found this:

https://stackoverflow.com/questions/7094574/how-to-specify-the-jaxb-version-in-maven-jaxb2-plugin

Additional question: If we're using the `org.jvnet.jaxb2.maven2` `maven-jaxb2-plugin`, why are we including the `com.sun.tools.xjc.maven2` `maven-jaxb-plugin` as a dep in pom.xml? The're two different plugins, no (and the former seems to be better according to this post: https://stackoverflow.com/a/2434603/375067

https://github.com/NeuroML/org.neuroml.model/blob/development/pom.xml#L177

**Comment by sanjayankur31** [comment]
@pgleeson : this needs your Java knowledge :angel:

**Comment by pgleeson** [comment]
This can certainly be fixed with some updates of java libraries, but it's related to the issues where Geppetto needs a slightly diffeerent version of some (JAXB related) libraries for use on OSB: https://github.com/OpenSourceBrain/geppetto-osb/issues/325.

At the moment, Geppetto compatible versions of java nml libraries are in the experimental branches. Changes from dev/master need to be merged into those branches, but we need to be careful not to break it for geppetto. Work to do after the hackathon (and v2.1 release)...

**Comment by sanjayankur31** [comment]
Sounds good. Maybe we target this for the 2.1.1 patch release?

**Comment by thorstenhater** [comment]
I just ran into this:
```
Validating: /Users/hater/src/nml2/jNeuroMLJar/../nml-simple-ion-channels.xml
Oct 16, 2021 10:26:15 AM com.sun.xml.bind.v2.runtime.reflect.opt.Injector <clinit>
SEVERE: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
[...]
```
but here it results in complete failure.

**Comment by sanjayankur31** [comment]
Thanks @thorstenhater : I think it's time we dug into this and fixed it. What version of java are you on please?

I'm currently on:

```
$ java --version
java 11.0.4 2019-07-16 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.4+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.4+10-LTS, mixed mode)
```

**Comment by sanjayankur31** [comment]
Some more info on this particular issue:

https://linuxpip.org/an-illegal-reflective-access-operation-has-occurred/

It documents a workaround for newer Java releases:


Permit illegal reflective access
Recent JDK versions still, by default, permits illegal access. Alternatively, in future releases, you can pass `--illegal-access=permit` to the script and it would opens every package in every explicit module to code in all unnamed modules, i.e., code on the class path, just as `--permit-illegal-access` does today.

**Comment by pgleeson** [comment]
Fixed now. Tests on Java 16 & 17, as well as on Linux, Mac and win have been added for full jnml stack, e.g. here: https://github.com/NeuroML/jNeuroML/actions/runs/1499130290
