### ISSUE TITLE
Generating output (.mod files etc.) outside of source directory

### ISSUE THREAD

**Issue by wvangeit** [NeuroML/jNeuroML#9]
Would it possible to add an option to the jnml script that allows one to put the generated model files (e.g. .mod files) in another directory.
As a temporary solution I created the following Python wrapper to the jnml command:
https://github.com/wvangeit/jNeuroML/blob/development/pyjnml
that more or less supports this feature.

**Comment by JustasB** [comment]
Yes, I would like this too

**Comment by pgleeson** [comment]
Added a quick & dirty implementation of this here in development: https://github.com/NeuroML/jNeuroML/commit/b38828122396e3bb5a88ffa60c007f80a7f87995

jnml LEMS_NML2_Ex0_IaF.xml -neuron -run -nogui -outputdir /tmp/nnnn/

will work, but 

jnml LEMS_NML2_Ex0_IaF.xml -neuron -run -outputdir /tmp/nnnn/

still hangs
