### ISSUE TITLE
ContentError: No runnable components have been specified

### ISSUE THREAD

**Issue by Aman123lug** [NeuroML/jNeuroML#91]
**Describe the bug**
When i try to run this ./jnml LEMS_lorenz.xml i am getting this error in my other pc also

**To Reproduce**
.ContentError: No runnable components have been specified

**Expected behavior**
I am trying to  simulate LEMS model 
Also Downloading ZIP from release found Virus my Browser stop the downloading don't know why

**Observed behavior**
![WhatsApp Image 2023-03-29 at 17 46 38](https://user-images.githubusercontent.com/94223645/228532697-c6d9a050-cbd8-4f90-9bd8-0be987886406.jpg)

**System information:**
 - OS: [Windows 11]
 - Java version (11)
 - Version of tools in use  (from `jnml -h`)

**Comment by sanjayankur31** [comment]
Hi @Aman123lug , thanks for the report. This isn't a jlems error. The LEMS file you are trying to simulate does not have any runnable components in it (as the error says). This implies that no simulation has been defined in the LEMS file, it's only a model. Can you please check the LEMS file?

If this is the [example from the docs](https://docs.neuroml.org/Userdocs/ExtendingNeuroMLv2WithLEMS.html), that does not have a runnable component---it only defines a new component type. So if you want to simulate that, you need to add the Simulation element. Please see this example:
